const names = [
    'Kussolj már bazdmeg',
    'Te geci hülye vagy',
    'Autista',
    'Wannabe Petőfi',
    'Piton professzor',
    'Whispertom',
    'Peti fogd már be geci',
    'Dzsudzsák az arab',
    'CR7',
    'KodiákCSGO',
    'TheVrJani',
    'Enedek Belek',
    'Setőfi Pándor',
    'Mókai Jór',
    'Csaba Mid MVP',
    'VV Aurélió',
    'VV Soma',
    'Aziz az igazi',
    'Cannavaro',
    'Gervetti Néza',
    'Janó szakáll nélkül',
    'Laci bácsi (aki már dead xd)',
    'José Mourinho',
    'Norina',
    'Tipszmiksz Csabi (RIP)',
    'Berki Mazsi',
    'G.W.M polgári nevén Varga Márk',
    'Csuti',
    'LL Junior fia (RIP)',
    'Köcsög xd',
    'Turbó Titán',
    'Jakab Péter',
    'Márki make some motherfuckin noise Péter',
    'Fefe faterja a veresi tóban',
    'Sárosi Laci bá',
    'M. Mátyás',
];

export default names;
