const names = [
    'Kussolj már bazdmeg',
    'Te geci hülye vagy',
    'Autista',
    'Wannabe Petőfi',
    'Piton professzor',
    'Whispertom',
    'Peti fogd már be geci',
    'Dzsudzsák az arab',
    'CR7',
    'KodiákCSGO',
    'TheVrJani',
    'Enedek Belek',
    'Setőfi Pándor',
    'Mókai Jór',
    'Csaba Mid MVP',
    'VV Aurélió',
    'VV Soma',
    'Aziz az igazi',
    'Cannavaro',
    'Gervetti Néza',
    'Janó szakáll nélkül',
    'Laci bácsi (aki már dead xd)',
    'José Mourinho',
    'Norina',
    'Tipszmiksz Csabi (RIP)',
    'Berki Mazsi',
    'G.w.M polgári nevén Varga Márk',
    'Csuti',
    'LL Junior fia (RIP)',
    'Köcsög xd',
    'Turbó Titán',
    'Jakab Péter',
    'Márki make some noise Péter',
    'Fefe faterja a veresi tóban',
    'Sárosi Laci bá',
    'M. Mátyás',
    'Edi Andre',
    'Bajor Imre sálja',
    'Szászi Péter',
    'Kiss és állat',
    'Ádám',
    'Mendel Mátyás AMG Mercedes',
    'musszólíni szarik',
    'ptzttshpttrsz tsh',
    'pápópépápárárá',
    'keresett a ból',
    'jó',
    'balsors',
    'fezzo04',
    'áh cigány',
    'molnár lüküke karamel',
    'fater szemüvege',
    'belementek a corsába geci',
    'százszor kész',
    'robi halott papája (meghalt)',
    'csuja imre',
    'tányérba fosott a kutya',
    'tengeri százlábú',
    'hurkás',
    'lencsefőzelékes cigány pina',
    'csomorika',
    'féreg',
    'golyók robi kezében',
    'erwin rommel',
    'Ács Dániel 444',
    'Fábián Tamás telex.hu',
    'Radamel Falcao',
    'Idi Amin Dada',
    'türkizkék labdák',
    'atatürk',
    'szekuriti',
    'kórcsi',
    '﷽﷽﷽﷽﷽﷽﷽',
    '5dik fehér monszter',
    '䲜䲜䲜䲜䲜䲜䲜䲜䲜䲜䲜',
    'csuran csepen halotad má ? :D',
    'száid',
    'juli ádám',
    'mevde',
    'szunog faszát ved be xD',
    'fasz fej',
    'faszát ved be',
    'faszát ved be xD',
    'faszát ved be :D',
    'faszát ved be XD',
    'faszát ved be 😂',
    'faszát ved be 😍',
    'faszát ved be 😘',
    'faszát ved be 😜',
    'faszát ved be 😝',
    'faszát ved be 😳',
    'faszát ved be 🤣',
    'faszát ved be 🤪',
    'faszát ved be 🥰',
    'faszát ved be 🥳',
    'faszát ved be 🥴',
    'faszát ved be 🥵',
    'faszát ved be 🥶',
    'faszát ved be 🥺',
    'faszát ved be 🧐',
    'faszát ved be 🧑‍🤝‍🧑',
    '🧑‍🤝‍🧑',
    '🧑‍🤝‍🧑🧑‍🤝‍🧑',
];

export default names;

